# Generated by Django 3.1.5 on 2021-01-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210111_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='language',
        ),
    ]
