# Generated by Django 3.1.5 on 2021-01-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210111_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
