# Generated by Django 3.1.5 on 2021-01-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210111_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_title',
            new_name='title',
        ),
    ]
