# Generated by Django 3.1.5 on 2021-01-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210112_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='categories',
        ),
        migrations.AddField(
            model_name='snippet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='core.category'),
            preserve_default=False,
        ),
    ]
